name: CI
on:
  push:
    branches:
    - main

jobs:
  split-upm:
    permissions:
      contents: write
    name: split upm branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: split upm branch
      run: |
        git subtree split -P "$PKG_ROOT" -b upm
        git push -u origin upm
      env:
        PKG_ROOT: Packages/tw.bogay.scene-audio-manager
